
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/** Name: Anupama Bhatta
 *  Date: 05/06/2019
 *  Description: Develop Tic-Tac-Toe game that uses Algorithm Engine Library.
 */

public class UI_Enter extends javax.swing.JFrame 
{
    public UI_Enter() 
    {  
        setFormUIDefaults();
        initComponents();        
        lblNameRequired.setVisible(false);
        
        try
        {
            String userName = System.getProperty("user.name");
            txtName.setText(userName);   
        } catch(Exception e)
        {
            
        }
        
        populateWhoGoesFirst();
    }
    
    private void setFormUIDefaults()
    {
        setResizable(false);
        setPosition();
        setAlwaysOnTop(true);
        setBG("/images/WesleyanBG.jpg");
    }
    
    private void setPosition() //put the form in the middle of the screen
    {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
    }
    
    private void setBG(String sImageName)
    {
        setContentPane(new JLabel(new ImageIcon(getClass().getResource(sImageName))));
    }
   
    private void populateWhoGoesFirst()
    {
        String computerUserName = "Computer";
        String selectedValue = cboFirstMove.getSelectedItem().toString();
        
        String userName = "You";
        
        if (!txtName.getText().isEmpty())
            userName = txtName.getText();
        
        cboFirstMove.removeAllItems();
        cboFirstMove.addItem(new String(""));
        cboFirstMove.addItem(new String(userName));
        cboFirstMove.addItem(new String(computerUserName));
        
        if (!selectedValue.isEmpty())
        {
            if (!selectedValue.equalsIgnoreCase(computerUserName))
                cboFirstMove.setSelectedItem(userName);
            else
                cboFirstMove.setSelectedItem(computerUserName);
        }
    }
    
    private int getDifficultyLevel()
    {
        String difficulty = cboDifficultyLevel.getSelectedItem().toString();
        if (difficulty.equalsIgnoreCase("Easy"))
            return 1;
        if (difficulty.equalsIgnoreCase("Medium"))
            return 2;
        if (difficulty.equalsIgnoreCase("Hard"))
            return 3;
        
        return 0;
    }
   
    private void lblPlayNormal()
    {
        if (lblPlay.isEnabled())
        {
            lblPlay.setBackground(new java.awt.Color(255, 255, 255));
            lblPlay.setForeground(new java.awt.Color(64, 40, 84));
        }
    }
    
    private void lblPlayHover()
    {
        if (lblPlay.isEnabled())
        {
            lblPlay.setBackground(new java.awt.Color(64, 40, 84));
            lblPlay.setForeground(new java.awt.Color(255, 255, 255));
        }
    }  
    
    private int getGridSize() // method that returns the grid size
    {
        String size = cboCells.getSelectedItem().toString();
        int iSize = size.charAt(0)-'0';
        return iSize;
    }
    
    private boolean validateInput()
    {
        populateWhoGoesFirst();
        if (!validateName())
        {
            lblPlay.setEnabled(false);
            lblPlay.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            return false;
        }
        else
        {
            lblPlay.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            lblPlay.setEnabled(true);
            return true;
        }
    }
    
    private boolean validateName()
    {
        return !AuxPackage.AuxValidatorForm.isEmpty(txtName, lblNameRequired, "PLEASE ENTER YOUR NAME");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPlay = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDifficulty = new javax.swing.JLabel();
        lblCells = new javax.swing.JLabel();
        lblWhoGoesFirst = new javax.swing.JLabel();
        cboDifficultyLevel = new javax.swing.JComboBox<>();
        cboCells = new javax.swing.JComboBox<>();
        cboFirstMove = new javax.swing.JComboBox<>();
        lblNameRequired = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 40, 84));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 90));

        pnlInput.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 40, 84));
        jLabel2.setText("Enter your name:");

        lblPlay.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        lblPlay.setForeground(new java.awt.Color(64, 40, 84));
        lblPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlay.setText("PLAY");
        lblPlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 40, 84), 4));
        lblPlay.setOpaque(true);
        lblPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlayMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPlayMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPlayMouseEntered(evt);
            }
        });

        txtName.setForeground(new java.awt.Color(64, 40, 84));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 40, 84), 2));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        lblDifficulty.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblDifficulty.setForeground(new java.awt.Color(64, 40, 84));
        lblDifficulty.setText("Difficulty");

        lblCells.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblCells.setForeground(new java.awt.Color(64, 40, 84));
        lblCells.setText("Cells");

        lblWhoGoesFirst.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblWhoGoesFirst.setForeground(new java.awt.Color(64, 40, 84));
        lblWhoGoesFirst.setText("Who Goes First?");

        cboDifficultyLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));
        cboDifficultyLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDifficultyLevelActionPerformed(evt);
            }
        });

        cboCells.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3*3", "4*4", "5*5" }));

        cboFirstMove.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNameRequired.setBackground(new java.awt.Color(153, 0, 0));
        lblNameRequired.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameRequired.setText("Name Required");

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputLayout.createSequentialGroup()
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInputLayout.createSequentialGroup()
                                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboCells, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCells, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWhoGoesFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboFirstMove, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(pnlInputLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNameRequired, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                        .addGap(55, 55, 55))))
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblNameRequired, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCells, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWhoGoesFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(cboCells)
                    .addComponent(cboDifficultyLevel)
                    .addComponent(cboFirstMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        getContentPane().add(pnlInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 470, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void cboDifficultyLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDifficultyLevelActionPerformed

    }//GEN-LAST:event_cboDifficultyLevelActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        validateInput();
    }//GEN-LAST:event_txtNameKeyReleased

    private void lblPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMouseClicked
        if (validateInput())
        {
            String userName = txtName.getText();
            String whoGoesFirst = cboFirstMove.getSelectedItem().toString();
            boolean userGoesFirst = userName.equalsIgnoreCase(whoGoesFirst);
            int difficulty = getDifficultyLevel();
            
            (new UI_Game(getGridSize(), userName, userGoesFirst, difficulty)).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_lblPlayMouseClicked
    
    private void lblPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMouseEntered
        lblPlayHover();
    }//GEN-LAST:event_lblPlayMouseEntered

    private void lblPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMouseExited
        lblPlayNormal();
    }//GEN-LAST:event_lblPlayMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Enter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCells;
    private javax.swing.JComboBox<String> cboDifficultyLevel;
    private javax.swing.JComboBox<String> cboFirstMove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCells;
    private javax.swing.JLabel lblDifficulty;
    private javax.swing.JLabel lblNameRequired;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblWhoGoesFirst;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
